version: '3.8'

services:
  database:
    image: postgres:16.0-alpine
    container_name: vantar_db
    restart: unless-stopped
    networks: 
      - vantar_net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - vantar-todo:/var/lib/postgresql/data
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        HASH: ${HASH}
        SECRET: ${SECRET}
        CLIENT_ID: ${CLIENT_ID}
        CLIENT_SECRET: ${CLIENT_SECRET}
        CB_URL: ${CB_URL}
        AT_TIME: ${AT_TIME}
        RT_TIME: ${RT_TIME}
        RT_SECRET: ${RT_SECRET}
    container_name: vantar_api
    networks: 
      - vantar_net
    depends_on: 
      - database
    ports:
      - ${PORT}:${PORT}
    env_file: .env.docker

networks:
  vantar_net:
    driver: bridge

volumes:
  vantar-todo: